line-length = 120
target-version = "py313"
exclude = [
  ".venv",
  "apps/controller/.venv",
  "apps/essentials/.venv",
  ".claude",
]

[lint]
select = [
  "E",   # pycodestyle errors
  "F",   # pyflakes
  "UP",  # pyupgrade
]
ignore = []
