apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.borgbackup.repoSecret.name }}
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  BORG_REPO: {{ .Values.borgbackup.repoSecret.BORG_REPO | quote }}
  BORG_PASSPHRASE: {{ .Values.borgbackup.repoSecret.BORG_PASSPHRASE | quote }}
