apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snapshot-borgbackup.snapshotConfigSecret" . }}
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  config.yaml: |
    namespace: {{ .Values.namespace.name }}
    hooks:
      pre: |
{{ (.Values.snapshot.hooks.pre | default "") | indent 8 }}
      post: |
{{ (.Values.snapshot.hooks.post | default "") | indent 8 }}
    snapshots:
{{ toYaml .Values.snapshot.snapshots | indent 6 }}
