apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-borg-backup.borgConfigSecret" . }}
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  config.yaml: |
    namespace: {{ .Values.namespace.name }}
    releaseName: {{ include "kube-borg-backup.fullname" . }}
    pod:
      image: {{ .Values.borgbackup.pod.image }}
      resources:
{{ toYaml .Values.borgbackup.pod.resources | indent 8 }}
    repoSecret: {{ .Values.borgbackup.repoSecret.name }}
    sshSecret: {{ .Values.borgbackup.sshSecret.name }}
    cachePVC: {{ .Values.borgbackup.cache.pvcName }}
    retention:
{{ toYaml .Values.borgbackup.retention | indent 6 }}
    backups:
{{ toYaml .Values.borgbackup.backups | indent 6 }}
