{{- range .Values.apps }}
{{- $_ := include "kube-borg-backup.validateAppName" .name -}}
{{- $borgConfig := fromJson (include "kube-borg-backup.mergeBorgConfig" (dict "root" $ "app" .)) -}}
{{- $_ := include "kube-borg-backup.validateBorgConfig" (dict "appName" .name "config" $borgConfig) -}}
{{- if $borgConfig.cache.create }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $borgConfig.cache.pvcName }}
  namespace: {{ .namespace }}
  labels:
    {{- include "kube-borg-backup.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
spec:
  accessModes:
{{- if $borgConfig.cache.accessModes }}
{{ toYaml $borgConfig.cache.accessModes | indent 4 }}
{{- else }}
    - ReadWriteOncePod
{{- end }}
  storageClassName: {{ $borgConfig.cache.storageClassName }}
  resources:
    requests:
      storage: {{ $borgConfig.cache.size }}
{{- end }}
{{ "" }}
{{- end }}
