apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "kube-borg-backup.fullname" . }}-snapshot
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "kube-borg-backup.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.snapshot.cron.schedule | quote }}
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: {{ .Values.snapshot.cron.startingDeadlineSeconds }}
  successfulJobsHistoryLimit: {{ .Values.snapshot.cron.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.snapshot.cron.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ .Values.snapshot.timeout }}
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: {{ .Values.serviceAccount.name }}
          restartPolicy: Never
          containers:
            - name: snapshot
              image: "{{ .Values.snapshot.image.repository }}:{{ .Values.snapshot.image.tag }}"
              imagePullPolicy: {{ .Values.snapshot.image.pullPolicy }}
              command: ["python", "-m", "kube_pvc_snapshot.main"]
              volumeMounts:
                - name: config
                  mountPath: /config
                  readOnly: true
          volumes:
            - name: config
              secret:
                secretName: {{ include "kube-borg-backup.snapshotConfigSecret" . }}
