{{- range .Values.apps }}
{{- $_ := include "kube-borg-backup.validateAppName" .name -}}
{{- if .createNamespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace }}
  labels:
    {{- include "kube-borg-backup.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
{{- end }}
{{- end }}
