{{- $namespaces := dict -}}
{{- range .Values.apps -}}
  {{- $_ := set $namespaces .namespace true -}}
{{- end -}}

---
# ClusterRole for reading cluster-scoped resources (StorageClasses)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.serviceAccount.name }}-clusterrole
  labels:
    {{- include "kube-borg-backup.labels" . | nindent 4 }}
rules:
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get","list"]

{{- range $namespace := keys $namespaces }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.serviceAccount.name }}
  namespace: {{ $namespace }}
  labels:
    {{- include "kube-borg-backup.labels" $ | nindent 4 }}
---
# ClusterRoleBinding for reading StorageClasses
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $.Values.serviceAccount.name }}-{{ $namespace }}-clusterrolebinding
  labels:
    {{- include "kube-borg-backup.labels" $ | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ $.Values.serviceAccount.name }}-clusterrole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.serviceAccount.name }}
    namespace: {{ $namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $.Values.serviceAccount.name }}-role
  namespace: {{ $namespace }}
  labels:
    {{- include "kube-borg-backup.labels" $ | nindent 4 }}
rules:
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["create","get","list","delete","patch","watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create","get","list","delete","patch","watch"]
  - apiGroups: [""]
    resources: ["pods","pods/log","pods/exec"]
    verbs: ["create","get","list","delete","patch","watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create","get","list","delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $.Values.serviceAccount.name }}-rolebinding
  namespace: {{ $namespace }}
  labels:
    {{- include "kube-borg-backup.labels" $ | nindent 4 }}
roleRef:
  kind: Role
  name: {{ $.Values.serviceAccount.name }}-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.serviceAccount.name }}
    namespace: {{ $namespace }}
{{- end }}
