{{- range .Values.apps }}
{{- $_ := include "kube-borg-backup.validateAppName" .name -}}
{{- $snapshotConfig := fromJson (include "kube-borg-backup.mergeSnapshotConfig" (dict "root" $ "app" .)) -}}
{{- $_ := include "kube-borg-backup.validateSnapshotConfig" (dict "appName" .name "config" $snapshotConfig) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-borg-backup.resourceName" (dict "appName" .name "resource" "snapshot-config") }}
  namespace: {{ .namespace }}
  labels:
    {{- include "kube-borg-backup.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
type: Opaque
stringData:
  config.yaml: |
    namespace: {{ .namespace }}
    snapshots:
      schedule: {{ $snapshotConfig.cron.schedule | quote }}
      retention:
        hourly: {{ $snapshotConfig.retention.hourly | default 0 }}
        daily: {{ $snapshotConfig.retention.daily | default 0 }}
        weekly: {{ $snapshotConfig.retention.weekly | default 0 }}
        monthly: {{ $snapshotConfig.retention.monthly | default 0 }}
      pvcs:
{{ toYaml $snapshotConfig.pvcs | indent 8 }}
{{- end }}
