{{- range .Values.apps }}
{{- $_ := include "kube-borg-backup.validateAppName" .name -}}
{{- $snapshotConfig := fromJson (include "kube-borg-backup.mergeSnapshotConfig" (dict "root" $ "app" .)) -}}
{{- $restoreConfig := fromJson (include "kube-borg-backup.mergeRestoreConfig" (dict "root" $ "app" .)) -}}
{{- $_ := include "kube-borg-backup.validateSnapshotConfig" (dict "appName" .name "config" $snapshotConfig) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-borg-backup.appResourceName" (dict "root" $ "appName" .name "resource" "snapshot-config") }}
  namespace: {{ .namespace }}
  labels:
    helm.sh/chart: {{ include "kube-borg-backup.chart" $ }}
    app.kubernetes.io/name: {{ include "kube-borg-backup.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    {{- if $.Chart.AppVersion }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/component: {{ .name }}
    # Custom managed-by for CLI config discovery (not Helm)
    app.kubernetes.io/managed-by: kube-borg-backup
type: Opaque
stringData:
  config.yaml: |
    namespace: {{ .namespace }}
    pod:
      image:
        repository: {{ $snapshotConfig.pod.image.repository }}
        tag: {{ $snapshotConfig.pod.image.tag | quote }}
        pullPolicy: {{ $snapshotConfig.pod.image.pullPolicy }}
    snapshots:
      schedule: {{ $snapshotConfig.cron.schedule | quote }}
      retention:
        hourly: {{ $snapshotConfig.retention.hourly | default 0 }}
        daily: {{ $snapshotConfig.retention.daily | default 0 }}
        weekly: {{ $snapshotConfig.retention.weekly | default 0 }}
        monthly: {{ $snapshotConfig.retention.monthly | default 0 }}
      pvcs:
{{ toYaml $snapshotConfig.pvcs | indent 8 }}
    {{- if or $restoreConfig.pod .restore }}
    restore:
      pod:
        image:
          repository: {{ $restoreConfig.pod.image.repository }}
          tag: {{ $restoreConfig.pod.image.tag | quote }}
          pullPolicy: {{ $restoreConfig.pod.image.pullPolicy }}
      {{- if .restore }}
      {{- if .restore.preHooks }}
      preHooks:
{{ toYaml .restore.preHooks | indent 8 }}
      {{- end }}
      {{- if .restore.postHooks }}
      postHooks:
{{ toYaml .restore.postHooks | indent 8 }}
      {{- end }}
      {{- end }}
    {{- end }}
{{ "" }}
{{- end }}
