apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-borg-backup.snapshotConfigSecret" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "kube-borg-backup.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    namespace: {{ .Values.namespace.name }}
    snapshots:
      schedule: {{ .Values.snapshot.cron.schedule | quote }}
      retention:
        hourly: {{ .Values.snapshot.retention.hourly | default 0 }}
        daily: {{ .Values.snapshot.retention.daily | default 0 }}
        weekly: {{ .Values.snapshot.retention.weekly | default 0 }}
        monthly: {{ .Values.snapshot.retention.monthly | default 0 }}
      pvcs:
{{ toYaml .Values.snapshot.pvcs | indent 8 }}
