## -- Namespace management
namespace:
  create: false
  name: somespace

## -- Name that ServiceAccount should have
serviceAccount:
  name: backup-account

## -- Snapshot CronJob configuration
snapshot:
  name: snapshot
  containerName: snapshot
  image:
    repository: ghcr.io/example/kube-pvc-snapshot
    tag: latest
    pullPolicy: IfNotPresent
  cron:
    schedule: "0 * * * *"
    concurrencyPolicy: Forbid
    startingDeadlineSeconds: 60
    successfulJobsHistoryLimit: 1
    failedJobsHistoryLimit: 1
  hooks:
    pre: |-
      echo "🗄️ Pausing db"
    post: |-
      echo "🗄️ Unpausing db"
  snapshots:
    - pvc: app-db-pvc
      class: longhorn
      keep:
        n: 12
        m_hours: 24
    - pvc: app-data-pvc
      class: smb
      keep:
        n: 12
        m_hours: 24

## -- BorgBackup configuration
borgbackup:
  name: borgbackup
  containerName: backup
  image:
    repository: ghcr.io/example/kube-snapshot-borgbackup
    tag: latest
    pullPolicy: IfNotPresent
  cron:
    schedule: "30 */6 * * *"
    concurrencyPolicy: Forbid
    startingDeadlineSeconds: 300
    successfulJobsHistoryLimit: 1
    failedJobsHistoryLimit: 1
    activeDeadlineSeconds: 86400
  pod:
    name: borg
    image: ghcr.io/example/borgbackup-essentials:latest
    timeoutSeconds: 86400
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
  borgFlags: "--keep-hourly=24 --keep-daily=7 --keep-weekly=4 --keep-monthly=3 --keep-yearly=1"
  cache:
    create: true
    pvcName: borg-cache
    storageClassName: openebs-hostpath
    size: 5Gi
  sshSecret:
    name: borg-ssh
    privateKey: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      somekey
      -----END OPENSSH PRIVATE KEY-----
  repoSecret:
    name: borg-secrets
    BORG_REPO: example
    BORG_PASSPHRASE: example
  backups:
    - name: app-db
      pvc: app-db-pvc
      class: longhorn
    - name: app-data
      pvc: app-data-pvc
      class: smb
