namespace: default
pod:
  name: borg
  image: borgbackup-essentials:latest
  repoSecret: borg-secrets
  sshSecret: borg-ssh
  cachePVC: borg-cache
  borgFlags: "--keep-last 3"
  timeoutSeconds: 3600
backups:
  - name: example
    pvc: example-pvc
    class: standard
