name: Container - Backup Runner

on:
  push:
    tags:
      - 'v*.*.*'        # Stable releases (v3.0.0)
      - 'v*.*.*-rc*'    # Release candidates (v3.0.0-rc1)
      - 'v*.*.*-beta*'  # Beta releases (v3.0.0-beta1)
      - 'v*.*.*-alpha*' # Alpha releases (v3.0.0-alpha1)

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract version from tag
        id: ver
        run: |
          # Extract version from tag (remove 'v' prefix)
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

          # Detect if pre-release (contains -, like 3.0.0-rc1)
          if [[ "$VERSION" == *"-"* ]]; then
            echo "is_prerelease=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_prerelease=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Multi-Arch Image
        uses: docker/build-push-action@v4
        with:
          context: apps/backup-runner
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/kube-borg-backup/backup-runner:${{ steps.ver.outputs.version }}
            ${{ steps.ver.outputs.is_prerelease == 'false' && format('ghcr.io/{0}/kube-borg-backup/backup-runner:latest', github.repository_owner) || '' }}

