name: Container - Essentials

on:
  push:
    branches:
      - main
    paths:
      - "apps/essentials/**"
      - ".github/workflows/essentials-image.yaml"

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Read project version
        id: ver
        run: |
          echo "version=$(cat apps/essentials/VERSION)" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Multi-Arch Image
        uses: docker/build-push-action@v4
        with:
          context: apps/essentials
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/kube-borg-backup-essentials:latest
            ghcr.io/${{ github.repository_owner }}/kube-borg-backup-essentials:${{ steps.ver.outputs.version }}
