name: Lint Helm chart
on:
  pull_request:
    paths:
      - "charts/**"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with: { version: v3.17.0 }

      - name: Set up Python (for yamllint/yamale used by ct lint)
        uses: actions/setup-python@v5
        with: { python-version: "3.x", check-latest: true }

      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: List changed charts
        id: list
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then echo "changed=true" >> "$GITHUB_OUTPUT"; fi

      - name: Lint charts
        if: steps.list.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}
