name: Mypy Type Check

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/**/*.py'
      - 'mypy.ini'
      - 'apps/requirements-dev.txt'
  pull_request:
    branches: [ main ]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r apps/controller/requirements.txt -r apps/requirements-dev.txt

      - name: Run mypy
        run: mypy --config-file mypy.ini
