name: Release Helm Charts

on:
  push:
    tags:
      - 'v*.*.*'        # Stable releases (v3.0.0)
      - 'v*.*.*-rc*'    # Release candidates (v3.0.0-rc1)
      - 'v*.*.*-beta*'  # Beta releases (v3.0.0-beta1)
      - 'v*.*.*-alpha*' # Alpha releases (v3.0.0-alpha1)

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          skip_existing: true
          charts_dir: charts
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CR_RELEASE_NAME_TEMPLATE: "v{{ .Version }}"
          CR_GENERATE_RELEASE_NOTES: true
