name: Ruff Lint

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/**/*.py'
      - '.ruff.toml'
      - 'apps/requirements-dev.txt'
  pull_request:
    branches: [ main ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r apps/requirements-dev.txt

      - name: Run ruff
        run: ruff check apps/
